version: 0.2

env:
  variables:
    TF_VERSION: 1.2.9
    TF_APPLY: 0
    TF_PLAN: 1
    TF_TARGET: 0
    TF_PLAN_ARGS: ""
    TF_APPLY_ARGS: ""
    TARGETS: ()

phases:
  install:
    runtime-versions:
        python: 3.x
    commands:
      - wget --quiet https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_${TF_VERSION}_linux_amd64.zip

  build:
    commands:
      - codebuild-breakpoint
      - terraform init
      - terraform workspace select test
      - |
        if [[ TF_TARGET -eq 1 ]]; then
          TARGETS=($(cat test_targets.txt | while read line; do echo -n "-target=$line "; done))
          echo "TARGETS: ${TARGETS[@]}"
        else
          TARGETS=""
        fi
      - |
        if [[ $TF_PLAN -eq 1 ]]; then
          echo "TARGETS: ${TARGETS[@]}"
          terraform plan $TF_PLAN_ARGS ${TARGETS[@]}
        else
          echo "SKIP TERRAFORM PLAN"
        fi
      - |
        if [[ $TF_APPLY -eq 1 ]]; then
          terraform apply $TF_APPLY_ARGS ${TARGETS[@]}
        else
          echo "SKIP TERRAFORM APPLY"
        fi

  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"