version: 0.2

phases:
  install:
    commands:
      - echo "Installing nothing..."
      - ls -l

  build:
    commands:
      - codebuild-breakpoint

  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"